[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = ["corepack enable", "corepack prepare pnpm@latest --activate", "pnpm install --frozen-lockfile", "pnpm run build"]

[start]
cmd = "pnpm start"